# Generated by Django 5.0 on 2024-09-19 10:47

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklm', length=10, max_length=10, prefix='CCS2', unique=True)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='Category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
