# Generated by Django 5.0 on 2024-09-19 10:47

import django.db.models.deletion
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklm', length=10, max_length=10, prefix='CCS2', unique=True)),
                ('title', models.CharField(default='CCS2', max_length=100)),
                ('image', models.ImageField(upload_to='Category.jpg')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, null=True)),
                ('status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Address',
            },
        ),
        migrations.CreateModel(
            name='ChargingStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklm', length=10, max_length=20, prefix='', unique=True)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(default='charging_station.jpeg', upload_to='user_directory_path')),
                ('description', models.TextField(blank=True, default='This is the Charging Station', null=True)),
                ('price', models.DecimalField(decimal_places=2, default='1.99', max_digits=9999999999)),
                ('old_price', models.DecimalField(decimal_places=2, default='2.99', max_digits=9999999999)),
                ('specification', models.TextField(blank=True, null=True)),
                ('slot_status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('rejected', 'Rejected'), ('in_review', 'in Review'), ('disabled', 'Disabled')], default='in_review', max_length=10)),
                ('status', models.BooleanField(default=True)),
                ('in_stock', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('sku', shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=4, max_length=10, prefix='sku', unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(blank=True, null=True)),
                ('Category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stationoperator.category')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stationoperator.tags')),
            ],
            options={
                'verbose_name_plural': 'Charging Station',
            },
        ),
        migrations.CreateModel(
            name='SlotReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default='1.99', max_digits=9999999999)),
                ('paid_status', models.BooleanField(default=False)),
                ('booking_date', models.DateField(auto_now_add=True)),
                ('slot_status', models.CharField(choices=[('reserved', 'Slot Reserved'), ('completed', 'Charging Completed'), ('in_process', 'Booking in Process')], default='Booking in Process', max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'slot orders',
            },
        ),
        migrations.CreateModel(
            name='BookingSlots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_no', models.CharField(max_length=200)),
                ('slot_status', models.CharField(max_length=200)),
                ('item', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('qty', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default='1.99', max_digits=9999999999)),
                ('total', models.DecimalField(decimal_places=2, default='1.99', max_digits=9999999999)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stationoperator.slotreservation')),
            ],
            options={
                'verbose_name_plural': 'Booking Slots',
            },
        ),
        migrations.CreateModel(
            name='StationImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(default='station.jpg', upload_to='station-images')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('chargingstation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stationoperator.chargingstation')),
            ],
            options={
                'verbose_name_plural': 'Station Images',
            },
        ),
        migrations.CreateModel(
            name='StationReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, '⭐☆☆☆☆'), (2, '⭐⭐☆☆☆'), (5, '⭐⭐⭐⭐⭐'), (3, '⭐⭐⭐☆☆'), (4, '⭐⭐⭐⭐☆')], default=None)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stationoperator.chargingstation')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklm', length=10, max_length=10, prefix='CCS2', unique=True)),
                ('title', models.CharField(default='TATA', max_length=100)),
                ('image', models.ImageField(default='vendor.jpeg', upload_to='user_directory_path')),
                ('description', models.TextField(blank=True, default='iam amazinf vendor', null=True)),
                ('address', models.CharField(default='123 Main Street london', max_length=100)),
                ('contact', models.CharField(default='1 +91 777 777 777', max_length=100)),
                ('chat_resp_time', models.CharField(default='100', max_length=100)),
                ('charging_efficiency', models.CharField(default='100', max_length=100)),
                ('station_rating', models.CharField(default='100', max_length=100)),
                ('reservation_cancellation_window', models.CharField(default='100', max_length=100)),
                ('maintenance_period', models.CharField(default='100', max_length=100)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stationoperator.chargingstation')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
