# Generated by Django 5.0 on 2024-09-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationoperator', '0002_remove_chargingstation_tags_alter_category_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargingstation',
            name='slot_status',
            field=models.CharField(choices=[('in_review', 'in Review'), ('disabled', 'Disabled'), ('published', 'Published'), ('rejected', 'Rejected'), ('draft', 'Draft')], default='in_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='stationreview',
            name='rating',
            field=models.IntegerField(choices=[(2, '⭐⭐☆☆☆'), (5, '⭐⭐⭐⭐⭐'), (3, '⭐⭐⭐☆☆'), (4, '⭐⭐⭐⭐☆'), (1, '⭐☆☆☆☆')], default=None),
        ),
    ]
