# Generated by Django 5.0 on 2024-09-19 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationoperator', '0003_alter_chargingstation_slot_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargingstation',
            name='slot_status',
            field=models.CharField(choices=[('published', 'Published'), ('draft', 'Draft'), ('in_review', 'in Review'), ('disabled', 'Disabled'), ('rejected', 'Rejected')], default='in_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='slotreservation',
            name='slot_status',
            field=models.CharField(choices=[('reserved', 'Slot Reserved'), ('in_process', 'Booking in Process'), ('completed', 'Charging Completed')], default='Booking in Process', max_length=30),
        ),
        migrations.AlterField(
            model_name='stationreview',
            name='rating',
            field=models.IntegerField(choices=[(3, '⭐⭐⭐☆☆'), (2, '⭐⭐☆☆☆'), (4, '⭐⭐⭐⭐☆'), (1, '⭐☆☆☆☆'), (5, '⭐⭐⭐⭐⭐')], default=None),
        ),
    ]
