# Generated by Django 5.0 on 2024-09-20 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationoperator', '0009_alter_chargingstation_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chargingstation',
            old_name='Category',
            new_name='category',
        ),
        migrations.AddField(
            model_name='chargingstation',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stationoperator.vendor'),
        ),
        migrations.AlterField(
            model_name='chargingstation',
            name='slot_status',
            field=models.CharField(choices=[('in_review', 'in Review'), ('disabled', 'Disabled'), ('published', 'Published'), ('rejected', 'Rejected'), ('draft', 'Draft')], default='in_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='slotreservation',
            name='slot_status',
            field=models.CharField(choices=[('reserved', 'Slot Reserved'), ('completed', 'Charging Completed'), ('in_process', 'Booking in Process')], default='Booking in Process', max_length=30),
        ),
        migrations.AlterField(
            model_name='stationreview',
            name='rating',
            field=models.IntegerField(choices=[(5, '⭐⭐⭐⭐⭐'), (3, '⭐⭐⭐☆☆'), (2, '⭐⭐☆☆☆'), (1, '⭐☆☆☆☆'), (4, '⭐⭐⭐⭐☆')], default=None),
        ),
    ]
