# Generated by Django 5.0 on 2024-09-20 20:28

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationoperator', '0011_alter_chargingstation_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcde123', length=10, max_length=10, prefix='CCS2', unique=True),
        ),
        migrations.AlterField(
            model_name='chargingstation',
            name='slot_status',
            field=models.CharField(choices=[('published', 'Published'), ('disabled', 'Disabled'), ('rejected', 'Rejected'), ('draft', 'Draft'), ('in_review', 'in Review')], default='in_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='slotreservation',
            name='slot_status',
            field=models.CharField(choices=[('completed', 'Charging Completed'), ('in_process', 'Booking in Process'), ('reserved', 'Slot Reserved')], default='Booking in Process', max_length=30),
        ),
        migrations.AlterField(
            model_name='stationreview',
            name='rating',
            field=models.IntegerField(choices=[(2, '⭐⭐☆☆☆'), (3, '⭐⭐⭐☆☆'), (4, '⭐⭐⭐⭐☆'), (5, '⭐⭐⭐⭐⭐'), (1, '⭐☆☆☆☆')], default=None),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcde123', length=10, max_length=10, prefix='CCS2', unique=True),
        ),
    ]
