# Generated by Django 5.0 on 2024-09-20 20:31

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationoperator', '0012_alter_category_cid_alter_chargingstation_slot_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargingstation',
            name='csid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcde123', length=10, max_length=20, prefix='', unique=True),
        ),
        migrations.AlterField(
            model_name='chargingstation',
            name='sku',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcd123', length=4, max_length=10, prefix='CS', unique=True),
        ),
        migrations.AlterField(
            model_name='chargingstation',
            name='slot_status',
            field=models.CharField(choices=[('published', 'Published'), ('rejected', 'Rejected'), ('in_review', 'in Review'), ('disabled', 'Disabled'), ('draft', 'Draft')], default='in_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='slotreservation',
            name='slot_status',
            field=models.CharField(choices=[('in_process', 'Booking in Process'), ('completed', 'Charging Completed'), ('reserved', 'Slot Reserved')], default='Booking in Process', max_length=30),
        ),
        migrations.AlterField(
            model_name='stationreview',
            name='rating',
            field=models.IntegerField(choices=[(3, '⭐⭐⭐☆☆'), (2, '⭐⭐☆☆☆'), (5, '⭐⭐⭐⭐⭐'), (4, '⭐⭐⭐⭐☆'), (1, '⭐☆☆☆☆')], default=None),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcde123', length=10, max_length=10, prefix='C', unique=True),
        ),
    ]
