# Generated by Django 5.0 on 2024-09-20 20:33

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationoperator', '0013_alter_chargingstation_csid_alter_chargingstation_sku_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcde123', length=10, max_length=20, prefix='CCS2', unique=True),
        ),
        migrations.AlterField(
            model_name='chargingstation',
            name='slot_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_review', 'in Review'), ('rejected', 'Rejected'), ('published', 'Published'), ('disabled', 'Disabled')], default='in_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='slotreservation',
            name='slot_status',
            field=models.CharField(choices=[('completed', 'Charging Completed'), ('reserved', 'Slot Reserved'), ('in_process', 'Booking in Process')], default='Booking in Process', max_length=30),
        ),
        migrations.AlterField(
            model_name='stationreview',
            name='rating',
            field=models.IntegerField(choices=[(5, '⭐⭐⭐⭐⭐'), (1, '⭐☆☆☆☆'), (2, '⭐⭐☆☆☆'), (4, '⭐⭐⭐⭐☆'), (3, '⭐⭐⭐☆☆')], default=None),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcde123', length=10, max_length=20, prefix='V', unique=True),
        ),
    ]
