# Generated by Django 5.0 on 2024-09-22 05:52

import stationoperator.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationoperator', '0023_alter_chargingstation_slot_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='cover_image',
            field=models.ImageField(default='vendor.jpg', upload_to=stationoperator.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='chargingstation',
            name='slot_status',
            field=models.CharField(choices=[('in_review', 'in Review'), ('published', 'Published'), ('rejected', 'Rejected'), ('draft', 'Draft'), ('disabled', 'Disabled')], default='in_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='slotreservation',
            name='slot_status',
            field=models.CharField(choices=[('reserved', 'Slot Reserved'), ('in_process', 'Booking in Process'), ('completed', 'Charging Completed')], default='Booking in Process', max_length=30),
        ),
        migrations.AlterField(
            model_name='stationreview',
            name='rating',
            field=models.IntegerField(choices=[(2, '⭐⭐☆☆☆'), (5, '⭐⭐⭐⭐⭐'), (3, '⭐⭐⭐☆☆'), (4, '⭐⭐⭐⭐☆'), (1, '⭐☆☆☆☆')], default=None),
        ),
    ]
