# Generated by Django 5.0 on 2024-09-22 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationoperator', '0025_rename_data_vendor_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargingstation',
            name='slot_status',
            field=models.CharField(choices=[('rejected', 'Rejected'), ('published', 'Published'), ('draft', 'Draft'), ('in_review', 'in Review'), ('disabled', 'Disabled')], default='in_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='slotreservation',
            name='slot_status',
            field=models.CharField(choices=[('in_process', 'Booking in Process'), ('completed', 'Charging Completed'), ('reserved', 'Slot Reserved')], default='Booking in Process', max_length=30),
        ),
        migrations.AlterField(
            model_name='stationreview',
            name='rating',
            field=models.IntegerField(choices=[(4, '⭐⭐⭐⭐☆'), (2, '⭐⭐☆☆☆'), (3, '⭐⭐⭐☆☆'), (5, '⭐⭐⭐⭐⭐'), (1, '⭐☆☆☆☆')], default=None),
        ),
    ]
