# Generated by Django 5.0 on 2024-09-22 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationoperator', '0026_alter_chargingstation_slot_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargingstation',
            name='slot_status',
            field=models.CharField(choices=[('disabled', 'Disabled'), ('rejected', 'Rejected'), ('published', 'Published'), ('draft', 'Draft'), ('in_review', 'in Review')], default='in_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='slotreservation',
            name='slot_status',
            field=models.CharField(choices=[('reserved', 'Slot Reserved'), ('completed', 'Charging Completed'), ('in_process', 'Booking in Process')], default='Booking in Process', max_length=30),
        ),
        migrations.AlterField(
            model_name='stationimages',
            name='chargingstation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='station_images', to='stationoperator.chargingstation'),
        ),
        migrations.AlterField(
            model_name='stationreview',
            name='rating',
            field=models.IntegerField(choices=[(3, '⭐⭐⭐☆☆'), (2, '⭐⭐☆☆☆'), (1, '⭐☆☆☆☆'), (5, '⭐⭐⭐⭐⭐'), (4, '⭐⭐⭐⭐☆')], default=None),
        ),
    ]
