# Generated by Django 5.0 on 2024-09-22 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationoperator', '0028_alter_chargingstation_slot_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargingstation',
            name='slot_status',
            field=models.CharField(choices=[('in_review', 'in Review'), ('disabled', 'Disabled'), ('published', 'Published'), ('draft', 'Draft'), ('rejected', 'Rejected')], default='in_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='slotreservation',
            name='slot_status',
            field=models.CharField(choices=[('completed', 'Charging Completed'), ('in_process', 'Booking in Process'), ('reserved', 'Slot Reserved')], default='Booking in Process', max_length=30),
        ),
        migrations.AlterField(
            model_name='stationreview',
            name='rating',
            field=models.IntegerField(choices=[(2, '⭐⭐☆☆☆'), (5, '⭐⭐⭐⭐⭐'), (1, '⭐☆☆☆☆'), (3, '⭐⭐⭐☆☆'), (4, '⭐⭐⭐⭐☆')], default=None),
        ),
    ]
