# Generated by Django 5.0 on 2024-09-23 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationoperator', '0029_alter_chargingstation_slot_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingstation',
            name='Charging_capacity',
            field=models.CharField(blank='True', default='CCS, >100 kW', max_length=100, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='chargingstation',
            name='Charging_time',
            field=models.CharField(blank='True', default='24V', max_length=100, null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='chargingstation',
            name='installation_date',
            field=models.DateField(blank='True', null='True'),
            preserve_default='True',
        ),
        migrations.AddField(
            model_name='chargingstation',
            name='type',
            field=models.CharField(blank='True', default='CCS2', max_length=100, null='True'),
            preserve_default='True',
        ),
        migrations.AlterField(
            model_name='chargingstation',
            name='slot_status',
            field=models.CharField(choices=[('in_review', 'in Review'), ('published', 'Published'), ('disabled', 'Disabled'), ('rejected', 'Rejected'), ('draft', 'Draft')], default='in_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='chargingstation',
            name='specification',
            field=models.TextField(blank='True', null='True'),
        ),
        migrations.AlterField(
            model_name='slotreservation',
            name='slot_status',
            field=models.CharField(choices=[('reserved', 'Slot Reserved'), ('in_process', 'Booking in Process'), ('completed', 'Charging Completed')], default='Booking in Process', max_length=30),
        ),
        migrations.AlterField(
            model_name='stationreview',
            name='rating',
            field=models.IntegerField(choices=[(5, '⭐⭐⭐⭐⭐'), (1, '⭐☆☆☆☆'), (4, '⭐⭐⭐⭐☆'), (2, '⭐⭐☆☆☆'), (3, '⭐⭐⭐☆☆')], default=None),
        ),
    ]
