# Generated by Django 5.0 on 2024-09-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationoperator', '0030_chargingstation_charging_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargingstation',
            name='slot_status',
            field=models.CharField(choices=[('rejected', 'Rejected'), ('draft', 'Draft'), ('disabled', 'Disabled'), ('published', 'Published'), ('in_review', 'in Review')], default='in_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='slotreservation',
            name='slot_status',
            field=models.CharField(choices=[('in_process', 'Booking in Process'), ('completed', 'Charging Completed'), ('reserved', 'Slot Reserved')], default='Booking in Process', max_length=30),
        ),
        migrations.AlterField(
            model_name='stationreview',
            name='rating',
            field=models.IntegerField(choices=[(5, '⭐⭐⭐⭐⭐'), (3, '⭐⭐⭐☆☆'), (4, '⭐⭐⭐⭐☆'), (2, '⭐⭐☆☆☆'), (1, '⭐☆☆☆☆')], default=None),
        ),
    ]
