# Generated by Django 5.0 on 2024-09-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationoperator', '0031_alter_chargingstation_slot_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargingstation',
            name='slot_status',
            field=models.CharField(choices=[('published', 'Published'), ('draft', 'Draft'), ('disabled', 'Disabled'), ('in_review', 'in Review'), ('rejected', 'Rejected')], default='in_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='slotreservation',
            name='slot_status',
            field=models.CharField(choices=[('in_process', 'Booking in Process'), ('reserved', 'Slot Reserved'), ('completed', 'Charging Completed')], default='Booking in Process', max_length=30),
        ),
        migrations.AlterField(
            model_name='stationreview',
            name='rating',
            field=models.IntegerField(choices=[(3, '⭐⭐⭐☆☆'), (5, '⭐⭐⭐⭐⭐'), (1, '⭐☆☆☆☆'), (2, '⭐⭐☆☆☆'), (4, '⭐⭐⭐⭐☆')], default=None),
        ),
    ]
