# Generated by Django 5.0 on 2024-09-25 14:03

import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationoperator', '0034_alter_chargingstation_slot_status_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargingstation',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='chargingstation',
            name='slot_status',
            field=models.CharField(choices=[('disabled', 'Disabled'), ('in_review', 'in Review'), ('rejected', 'Rejected'), ('draft', 'Draft'), ('published', 'Published')], default='in_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='slotreservation',
            name='slot_status',
            field=models.CharField(choices=[('completed', 'Charging Completed'), ('in_process', 'Booking in Process'), ('reserved', 'Slot Reserved')], default='Booking in Process', max_length=30),
        ),
        migrations.AlterField(
            model_name='stationreview',
            name='rating',
            field=models.IntegerField(choices=[(5, '⭐⭐⭐⭐⭐'), (4, '⭐⭐⭐⭐☆'), (1, '⭐☆☆☆☆'), (3, '⭐⭐⭐☆☆'), (2, '⭐⭐☆☆☆')], default=None),
        ),
    ]
