# Generated by Django 5.0 on 2024-09-25 20:26

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationoperator', '0035_chargingstation_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargingstation',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='This is the Charging Station', null=True),
        ),
        migrations.AlterField(
            model_name='chargingstation',
            name='slot_status',
            field=models.CharField(choices=[('rejected', 'Rejected'), ('in_review', 'in Review'), ('published', 'Published'), ('disabled', 'Disabled'), ('draft', 'Draft')], default='in_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='chargingstation',
            name='specification',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank='True', null='True'),
        ),
        migrations.AlterField(
            model_name='slotreservation',
            name='slot_status',
            field=models.CharField(choices=[('in_process', 'Booking in Process'), ('reserved', 'Slot Reserved'), ('completed', 'Charging Completed')], default='Booking in Process', max_length=30),
        ),
        migrations.AlterField(
            model_name='stationreview',
            name='rating',
            field=models.IntegerField(choices=[(5, '⭐⭐⭐⭐⭐'), (2, '⭐⭐☆☆☆'), (4, '⭐⭐⭐⭐☆'), (1, '⭐☆☆☆☆'), (3, '⭐⭐⭐☆☆')], default=None),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='iam amazinf vendor', null=True),
        ),
    ]
