# Generated by Django 5.0 on 2024-09-25 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationoperator', '0036_alter_chargingstation_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargingstation',
            name='description',
            field=models.TextField(blank=True, default='This is the Charging Station', null=True),
        ),
        migrations.AlterField(
            model_name='chargingstation',
            name='slot_status',
            field=models.CharField(choices=[('rejected', 'Rejected'), ('published', 'Published'), ('draft', 'Draft'), ('disabled', 'Disabled'), ('in_review', 'in Review')], default='in_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='chargingstation',
            name='specification',
            field=models.TextField(blank='True', null='True'),
        ),
        migrations.AlterField(
            model_name='slotreservation',
            name='slot_status',
            field=models.CharField(choices=[('reserved', 'Slot Reserved'), ('in_process', 'Booking in Process'), ('completed', 'Charging Completed')], default='Booking in Process', max_length=30),
        ),
        migrations.AlterField(
            model_name='stationreview',
            name='rating',
            field=models.IntegerField(choices=[(2, '⭐⭐☆☆☆'), (1, '⭐☆☆☆☆'), (5, '⭐⭐⭐⭐⭐'), (4, '⭐⭐⭐⭐☆'), (3, '⭐⭐⭐☆☆')], default=None),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='description',
            field=models.TextField(blank=True, default='iam amazinf vendor', null=True),
        ),
    ]
