# Generated by Django 5.0 on 2024-09-26 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stationoperator', '0038_alter_chargingstation_slot_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargingstation',
            name='slot_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('rejected', 'Rejected'), ('published', 'Published'), ('in_review', 'in Review'), ('disabled', 'Disabled')], default='in_review', max_length=10),
        ),
        migrations.AlterField(
            model_name='stationreview',
            name='rating',
            field=models.IntegerField(choices=[(2, '⭐⭐☆☆☆'), (4, '⭐⭐⭐⭐☆'), (3, '⭐⭐⭐☆☆'), (1, '⭐☆☆☆☆'), (5, '⭐⭐⭐⭐⭐')], default=None),
        ),
    ]
